# Generated by Django 2.2.6 on 2019-11-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('musculo', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('num_ejercicios', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo', models.CharField(blank=True, max_length=100, null=True)),
                ('informativo', models.CharField(blank=True, max_length=100, null=True)),
                ('ejercicios', models.ManyToManyField(to='miapp.Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lema', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Noviembre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('objetivo', models.CharField(choices=[('Definicion', 'Definicion'), ('Mantenimiento', 'Mantenimiento'), ('Musculacion', 'Musculacion')], default='Mantenimiento', max_length=13)),
                ('num_dias', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('dias', models.ManyToManyField(to='miapp.EjercicioDia')),
            ],
        ),
        migrations.CreateModel(
            name='Editar_Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=6)),
                ('edad', models.IntegerField(default=18)),
                ('peso', models.DecimalField(decimal_places=1, default=60, max_digits=3)),
                ('altura', models.IntegerField(default=180)),
                ('objetivo', models.CharField(choices=[('Definicion', 'Definicion'), ('Mantenimiento', 'Mantenimiento'), ('Musculacion', 'Musculacion')], default='Mantenimiento', max_length=13)),
                ('actividad', models.CharField(choices=[('Nada de ejercicio', 'Nada de ejercicio'), ('Ejercicio Ligero', 'Ejercicio Ligero'), ('Ejercicio Moderado', 'Ejercicio Moderado'), ('Ejercicio Regular', 'Ejercicio Regular'), ('Ejercicio Intenso', 'Ejercicio Intenso')], default='Ejercicio Moderado', max_length=50)),
                ('ejercicios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Entrenamiento')),
                ('frase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Frase')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Año',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_año', models.CharField(blank=True, max_length=100, null=True)),
                ('enero', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('febrero', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=112)),
                ('marzo', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('abril', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('mayo', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('junio', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('julio', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('agosto', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('septiembre', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('octubre', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('noviembre', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('diciembre', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124)),
                ('ultimo_dia', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
