# Generated by Django 2.2.6 on 2019-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
