# Generated by Django 2.2.6 on 2019-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20191108_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciodia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
