# Generated by Django 2.2.3 on 2019-08-16 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('musculo', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('num_ejercicios', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo', models.CharField(blank=True, max_length=100, null=True)),
                ('informativo', models.CharField(blank=True, max_length=100, null=True)),
                ('ejercicios', models.ManyToManyField(null=True, to='miapp.Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lema', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('objetivo', models.CharField(choices=[('Definicion', 'Definicion'), ('Mantenimiento', 'Mantenimiento'), ('Musculacion', 'Musculacion')], default='Mantenimiento', max_length=13)),
                ('num_dias', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('dias', models.ManyToManyField(to='miapp.EjercicioDia')),
            ],
        ),
        migrations.CreateModel(
            name='Editar_Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=6)),
                ('edad', models.IntegerField(default=18)),
                ('peso', models.DecimalField(decimal_places=1, default=60, max_digits=3)),
                ('altura', models.IntegerField(default=180)),
                ('objetivo', models.CharField(choices=[('Definicion', 'Definicion'), ('Mantenimiento', 'Mantenimiento'), ('Musculacion', 'Musculacion')], default='Mantenimiento', max_length=13)),
                ('actividad', models.CharField(choices=[('Nada de ejercicio', 'Nada de ejercicio'), ('Ejercicio Ligero', 'Ejercicio Ligero'), ('Ejercicio Moderado', 'Ejercicio Moderado'), ('Ejercicio Regular', 'Ejercicio Regular'), ('Ejercicio Intenso', 'Ejercicio Intenso')], default='Ejercicio Moderado', max_length=50)),
                ('ejercicios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Entrenamiento')),
                ('frase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Frase')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
