# Generated by Django 2.2.3 on 2019-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_auto_20190817_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='año',
            name='abril',
            field=models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='agosto',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='diciembre',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='febrero',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=112),
        ),
        migrations.AddField(
            model_name='año',
            name='julio',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='junio',
            field=models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='marzo',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='mayo',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='noviembre',
            field=models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='octubre',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='septiembre',
            field=models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
        migrations.AddField(
            model_name='año',
            name='ultimo_dia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='año',
            name='enero',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=124),
        ),
    ]
